version: '3.1'


services:
  web01:
    image: nginx
    volumes:
      - ./nginx/node.conf:/etc/nginx/nginx.conf
      - ./app/index1.html:/var/www/html/index.html
    ports:
      - "8081:80"
    environment:
      - NGINX_HOST=webserver01
      - NGINX_PORT=80

  web02:
    image: nginx
    volumes:
      - ./nginx/node.conf:/etc/nginx/nginx.conf
      - ./app/index2.html:/var/www/html/index.html
    ports:
      - "8082:80"
    environment:
      - NGINX_HOST=webserver02
      - NGINX_PORT=80

  web03:
    image: nginx
    volumes:
      - ./nginx/node.conf:/etc/nginx/nginx.conf
      - ./app/index3.html:/var/www/html/index.html
    ports:
      - "8083:80"
    environment:
      - NGINX_HOST=webserver03
      - NGINX_PORT=80
    
  web04:
    image: nginx
    volumes:
      - ./nginx/node.conf:/etc/nginx/nginx.conf
      - ./app/index4.html:/var/www/html/index.html
    ports:
      - "8084:80"
    environment:
      - NGINX_HOST=webserver04
      - NGINX_PORT=80

  web05:
    image: nginx
    volumes:
      - ./nginx/node.conf:/etc/nginx/nginx.conf
      - ./app/index5.html:/var/www/html/index.html
    ports:
      - "8085:80"
    environment:
      - NGINX_HOST=webserver05
      - NGINX_PORT=80

  loadbalancer:
    image: nginx
    links:
      - web01
      - web02
      - web03
      - web04
      - web05
    volumes:
      - ./nginx/lb.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    
